/// <reference types='vitest' />
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig, loadEnv, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';

const outDir = './dist/spoticast';

/**
 * Apache config for the FTP hosting (tophost.it): HTTPS, SPA fallback so deep
 * links like /podcast/:id load the app, and caching rules (hashed assets are
 * immutable; the shell, service worker and charts must always revalidate).
 */
export function htaccess(base: string): string {
  return `# Generated by vite.config.mts — do not edit on the server.
Options -MultiViews
DirectoryIndex index.html
AddType application/manifest+json .webmanifest

# State files of the FTP deploy action (list of deployed files).
<Files ".ftp-deploy-sync-state.json">
  Require all denied
</Files>

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase ${base}

  # Spotify login and installable PWAs both require HTTPS.
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !=https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

  # Single-page app: unknown paths get index.html.
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^ index.html [L]
</IfModule>

<IfModule mod_headers.c>
  <FilesMatch "\\.(html|webmanifest|json)$|^(sw|registerSW)\\.js$">
    Header set Cache-Control "no-cache"
  </FilesMatch>
  <FilesMatch "-[A-Za-z0-9_-]{8}\\.(js|css)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
</IfModule>
`;
}

/** Short commit of the build, shown in Settings: CI sets GITHUB_SHA. */
function buildSha(): string {
  if (process.env.GITHUB_SHA) return process.env.GITHUB_SHA.slice(0, 7);
  try {
    return execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
  } catch {
    return 'dev';
  }
}

/**
 * Release version: the deploy workflow passes the release tag in APP_VERSION;
 * local builds describe HEAD from the nearest tag (e.g. v1.2.0-3-gabc1234).
 */
function buildVersion(): string {
  if (process.env.APP_VERSION) return process.env.APP_VERSION;
  try {
    return execSync('git describe --tags', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return 'dev';
  }
}

export type Channel = 'production' | 'beta';

export interface BuildInfo {
  version: string;
  sha: string;
  date: string;
  channel: Channel;
  /** GitHub Release page of the version (set by the deploy workflow). */
  releaseUrl?: string;
}

/** Served next to the app so a running version can tell what was deployed. */
function versionFile(info: BuildInfo): Plugin {
  return {
    name: 'spoticast:version',
    apply: 'build',
    closeBundle() {
      writeFileSync(
        resolve(import.meta.dirname, outDir, 'version.json'),
        `${JSON.stringify(info, null, 2)}\n`,
      );
    },
  };
}

function apacheConfig(base: string): Plugin {
  return {
    name: 'spoticast:htaccess',
    apply: 'build',
    closeBundle() {
      writeFileSync(
        resolve(import.meta.dirname, outDir, '.htaccess'),
        htaccess(base),
      );
    },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, import.meta.dirname, 'VITE_');
  const base = env.VITE_BASE || '/';
  const build: BuildInfo = {
    version: buildVersion(),
    sha: buildSha(),
    date: new Date().toISOString(),
    channel: env.VITE_CHANNEL === 'beta' ? 'beta' : 'production',
    releaseUrl: process.env.APP_RELEASE_URL || undefined,
  };

  return {
    root: import.meta.dirname,
    base,
    define: {
      __APP_BUILD__: JSON.stringify(build),
    },
    cacheDir: './node_modules/.vite/spoticast',
    // Spotify rejects "localhost" redirect URIs: use the loopback IP instead.
    server: {
      port: 4200,
      host: '127.0.0.1',
    },
    preview: {
      port: 4300,
      host: '127.0.0.1',
    },
    plugins: [
      react(),
      tailwindcss(),
      VitePWA({
        // The new service worker waits until the user taps "Update" (see
        // src/lib/pwa/update.ts, which also registers it).
        registerType: 'prompt',
        injectRegister: false,
        includeAssets: ['favicon.ico', 'apple-touch-icon-180x180.png'],
        manifest: {
          name: 'Spoticast',
          short_name: 'Spoticast',
          description: 'Podcast client for Spotify',
          theme_color: '#0f1115',
          background_color: '#0f1115',
          display: 'standalone',
          orientation: 'any',
          start_url: base,
          scope: base,
          icons: [
            { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
            { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
            { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
            {
              src: 'maskable-icon-512x512.png',
              sizes: '512x512',
              type: 'image/png',
              purpose: 'maskable',
            },
          ],
        },
        workbox: {
          navigateFallback: 'index.html',
          navigateFallbackDenylist: [new RegExp(`^${base}callback`)],
          runtimeCaching: [
            {
              // Cover art from Spotify's image CDN.
              urlPattern:
                /^https:\/\/([a-z0-9-]+\.scdn\.co|[a-z0-9-]+\.spotifycdn\.com)\/image\//,
              handler: 'CacheFirst',
              options: {
                cacheName: 'spotify-images',
                expiration: {
                  maxEntries: 500,
                  maxAgeSeconds: 60 * 60 * 24 * 30,
                },
                cacheableResponse: { statuses: [0, 200] },
              },
            },
            {
              urlPattern: /\/charts\/[a-z]{2}\.json$/,
              handler: 'StaleWhileRevalidate',
              options: { cacheName: 'charts' },
            },
          ],
        },
      }),
      apacheConfig(base),
      versionFile(build),
    ],
    build: {
      outDir,
      emptyOutDir: true,
      reportCompressedSize: true,
      commonjsOptions: {
        transformMixedEsModules: true,
      },
    },
    test: {
      name: 'spoticast',
      watch: false,
      globals: true,
      environment: 'jsdom',
      setupFiles: ['./src/test-setup.ts'],
      include: ['{src,tests}/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
      reporters: ['default'],
      coverage: {
        reportsDirectory: './coverage/spoticast',
        provider: 'v8' as const,
      },
    },
  };
});
